In [1]:
import numpy as np

# Creating Arrays

In [5]:
array_zeros = np.zeros(5)
array_ones = np.ones(5)
array_consts = np.full(5, 2.5)
array_zeros,array_ones,array_consts


(array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([2.5, 2.5, 2.5, 2.5, 2.5]))

**List to Array**

In [10]:
a = np.array([1, 3, 4, 5])
a


array([1, 3, 4, 5])

In [16]:
#accessing elements in array
element = a[2]
element

np.int64(4)

**Ranges**:
create an array with a range of elements

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
# arange(first number, last number, step size)
np.arange(2,9,2)

array([2, 4, 6, 8])

In [25]:
#creating array using linspace(for linear spacing)
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Multi-Dimensional arrays**

In [26]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])