In [2]:
import numpy as np

# Creating Arrays

In [5]:
array_zeros = np.zeros(5)
array_ones = np.ones(5)
array_consts = np.full(5, 2.5)
array_zeros,array_ones,array_consts


(array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([2.5, 2.5, 2.5, 2.5, 2.5]))

**List to Array**

In [10]:
a = np.array([1, 3, 4, 5])
a


array([1, 3, 4, 5])

In [16]:
#accessing elements in array
element = a[2]
element

np.int64(4)

**Ranges**:
create an array with a range of elements

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
# arange(first number, last number, step size)
np.arange(2,9,2)

array([2, 4, 6, 8])

In [25]:
#creating array using linspace(for linear spacing)
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Multi-Dimensional arrays**

In [26]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Indexing and Slicing Arrays**

In [6]:
arr = np.array([
    [2,3,4],
    [4,5,6]
])
first_row = arr[0] #gets the first row
first_column = arr[:, 0] #gets the first column
first_row, first_column

(array([2, 3, 4]), array([2, 4]))

**Random Numbers**

In [29]:
np.random.seed(5)
random = np.random.rand(3,2)
random

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386]])

In [31]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

**Element wise operations**

In [36]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
a*2

array([0, 2, 4, 6, 8])

In [40]:
a+(10*2-10)

array([10, 11, 12, 13, 14])

**Comparision operations**

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
a>=2

array([False, False,  True,  True,  True])

In [43]:
a<=2

array([ True,  True,  True, False, False])

**Summarizing Operations**

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.min()

np.int64(0)

In [47]:
a.max()

np.int64(4)

In [48]:
a.sum()

np.int64(10)

In [49]:
a.mean()

np.float64(2.0)

In [50]:
a.std()

np.float64(1.4142135623730951)