In [2]:
import numpy as np

# Vector Operations
formula:
If $(u = [u_1, u_2, u_3])$ and $(v = [v_1, v_2, v_3])$, then:


 &emsp; Result= $(u_{1}\times v_{1})+(u_{2}\times v_{2})+(u_{3}\times v_{3}))$

In [2]:
u = np.array([2,4,5])
2*u

array([ 4,  8, 10])

In [3]:
2+u

array([4, 6, 7])

**Vector-vector multiplication(dot product)**

In [33]:
u = np.array([4,5,6])
v = np.array([1,2,3])
v.shape[0]

3

In [ ]:
def vector_vector_multiplication(u, v):
    # assert u.ndim ==1 and v.ndim == 1, "inputs must be 1D arrays"
    assert u.shape[0] == v.shape[0], "vectors must have same length"
    return np.sum(u*v)       # Multiplies the vectors element-by-element first, then sums up the array.
    n = v.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i]*v[i]
    return result

    # return np.dot(u,v)    # The traditional function call for computing dot products.
    # return u @ v        # The @ Operator: The cleanest, standard syntax for matrix/vector multiplication in modern Python.

vector_vector_multiplication(u, v)

np.int64(32)

**Matrix-vector multiplication**
If a Matrix has a shape of $(M \times N)$ 

The Vector must have a shape of (N) 

The Output Vector will have a shape of (M)

In [41]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
u = np.array([1, 2, 3, 4])
X.shape
u.shape


(4,)

In [ ]:
def matrix_vector_multiplication(X,u):
    assert X.shape[1] == u.shape[0],  "Mismatch in rows and column"
    num_of_rows = X.shape[0]
    # num_of_columns = X.shape[1]
    result = np.zeros(num_of_rows)
    # for i in range(num_of_rows):
    #     for j in range(num_of_columns):
    #         result[i] = result[i] + X[i, j] * u[j]

    #for i in range(num_of_rows):
        #result[i] = np.sum(X[i]*u)       #takes rows of X one by one and multiplies with u and adds them
    #return result


    return X.dot(u)
matrix_vector_multiplication(X,u)

array([ 30,  70, 110])

**Matrix_Matrix Multiplication**

In [57]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
Y = np.array([
    [4, 3, 2, 1],
    [8, 7, 6, 5],
    [12, 11, 10, 9],
    [2,3,4,5]
])


In [54]:
def matrix_matrix_multiplicationn(X,Y):
    assert X.shape[1] == Y.shape[0], "dimension mismatch"
    num_of_rows = X.shape[0]
    num_of_columns = Y.shape[1]
    result = np.zeros((num_of_rows, num_of_columns))

    # for i in range(num_of_rows):                                #iterate through rows of X
    #     for j in range(num_of_columns):                         #iterate through columns of y
    #         for k in range(X.shape[1]):                         #step throughh the elements of row X[i] and column Y[:,j]
    #             result[i,j] = result[i, j] + X[i, k]*Y[k, j]
    # 
      
    return X @ Y
matrix_matrix_multiplicationn(X,Y)

array([[ 64,  62,  60,  58],
       [168, 158, 148, 138],
       [272, 254, 236, 218]])

**Identity matrix**

In [58]:
I  = np.eye(4)
I
X.dot(I)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

**Inverse**

In [79]:
Z = np.array([
    [1,4,3],
    [4,5,6],
    [7,8,9]
])


In [82]:
Zv = np.linalg.inv(Z)
Zv
Zv.dot(Z)


array([[ 1.00000000e+00,  0.00000000e+00,  1.11022302e-16],
       [-3.88578059e-16,  1.00000000e+00, -5.55111512e-17],
       [ 5.55111512e-16,  0.00000000e+00,  1.00000000e+00]])